---
spring:
  application:
    name: sentence
  cloud:
    config:
      uri: http://localhost:8001  # Expect the Spring Cloud Config server to be running on localhost, port 8001.  
server:
  port: 8020
  
management: 
  endpoints: 
    web: 
      exposure: 
        include: 'hystrix.stream'
        
